CREATE TABLE USER_A11Y_SETTINGS (
    USER_ID              RAW(16) PRIMARY KEY,
    CONTRAST_LEVEL       NUMBER(1) DEFAULT 0 NOT NULL,
    TEXT_SIZE_LEVEL       NUMBER(1) DEFAULT 0 NOT NULL,
    TEXT_SPACING_LEVEL    NUMBER(1) DEFAULT 0 NOT NULL,
    LINE_HEIGHT_LEVEL     NUMBER(1) DEFAULT 0 NOT NULL,
    TEXT_ALIGN            VARCHAR2(10) DEFAULT 'left' NOT NULL,
    SCREEN_READER         NUMBER(1) DEFAULT 0 NOT NULL,
    SMART_CONTRAST         NUMBER(1) DEFAULT 0 NOT NULL,
    HIGHLIGHT_LINKS        NUMBER(1) DEFAULT 0 NOT NULL,
    CURSOR_HIGHLIGHT       NUMBER(1) DEFAULT 0 NOT NULL,
    UPDATED_AT             TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_USER_A11Y_SETTINGS
        FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
);
